version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf
  - epub

build:
  image: latest  # Ensure this is the correct image for your needs
