version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  version: 3.12
  install:
    - requirements: requirements.txt

formats:
  - htmlzip
  - pdf
  - epub

build:
  image: latest
